### ISSUE TITLE
[Bug] Can not automatically start playing from USharpVideo

### ISSUE THREAD

**Issue by rakosi2** [UshioHiko/VRCVideoLibrary#1]
Will not autoplay videos with the video player USharpVideo. I can copy and paste but with copy off/automatic, the video does not start playing no matter how long I wait.
https://github.com/MerlinVR/USharpVideo

**Comment by Stoned-Code** [comment]
I haven't put in any compatability with Udon video players yet. I did get started on it.

**Comment by rakosi2** [comment]
For now, you may want to mention that in your README.md
