### ISSUE TITLE
[Bug] Unable to start video with USharpVideo if non-host but it is opened to anyone

### ISSUE THREAD

**Issue by rakosi2** [UshioHiko/VRCVideoLibrary#4]
USharpVideo can be opened for anyone to start playing videos not just the host but VRCVideoLibrary will still say that only Host can start the video.

**Comment by Stoned-Code** [comment]
After New Years, I'll get to work on fixing it. Though I've been having a bit of a hard time getting USharpVideo stuff to work properly.

**Comment by rakosi2** [comment]
No worries and take your time. Just wanted to make the Issues to make you aware of them and I am not forcing you to work on them.
