### ISSUE TITLE
Next Page and Copy Buttons in same position

### ISSUE THREAD

**Issue by RyanWolfe556** [UshioHiko/VRCVideoLibrary#5]
![image](https://user-images.githubusercontent.com/22670141/103933808-96a61180-50e9-11eb-98bf-42c439b62d81.png)

Both buttons overlap and cause the next page button to not function. 

Issue found in VRC release build 1032

**Comment by Jukebox-Zulu** [comment]
Same issue here. Any fix yet?

**Comment by Stoned-Code** [comment]
Did you make sure to update the mod? Cause I took care of that in a past version.

**Comment by Jukebox-Zulu** [comment]
> Did you make sure to update the mod? Cause I took care of that in a past version.

Just updated and it is fixed, so thank you! But just so you know, typically I update mods when MelonLoader tells me they are out of date, and right now it's saying that your mod is out of date and the current version is 0.6.4 while I'm running 1.0.5. That is probably why I hadn't updated it. Not sure if that's an issue on your end or MelonLoader, but thought I would let you know!

**Comment by RyanWolfe556** [comment]
> Did you make sure to update the mod? Cause I took care of that in a past version.

Apologies for late/closed reply, the linked dll in VRC Modding Discord is outdated. 

Confirmed fixed.
