### ISSUE TITLE
Hardcoded User ID

### ISSUE THREAD

**Issue by Anonymous-BCFED** [UshioHiko/VRCVideoLibrary#9]
https://github.com/UshioHiko/VRCVideoLibrary/blob/4678cdec8d056cddb8ce360c5bab3112cf8ab90e/VRCVideoLibrary/VideoLibrary/VideoLib.cs#L586

Why is your user ID referenced in this addon?

**Comment by Stoned-Code** [comment]
Oh, whoops, I think it's something I forgot to take out during debugging.
